{{- if .Values.agg.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-agg-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-agg
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}