{{- if .Values.auth.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpos-auth-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: helpos-auth
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: helpos-auth
  template:
    metadata:
      labels:
        app: helpos-auth
    spec:
      containers:
      - name: helpos-auth
        image: "{{ .Values.backend.image.repository }}/{{ .Values.auth.image }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 80
        {{- if .Values.auth.livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
            scheme: {{ .Values.livenessProbe.scheme }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
       - name: config-volume
         configMap:
           name: helpos-auth-configmap
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
{{- end }}