{{- if .Values.auth.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-auth
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}