{{- if .Values.cust.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-cust-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-cust
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}