{{- if .Values.dict.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-dict-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-dict
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}