{{- if .Values.fo.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-fo-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-fo
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}