apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpos-frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: helpos-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: helpos-frontend
  template:
    metadata:
      labels:
        app: helpos-frontend
    spec:
      containers:
      - name: helpos-frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: 80
        
