apiVersion: v1
kind: Service
metadata:
  name: helpos-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-frontend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
