apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpos-frontend-service
  namespace: {{ .Values.namespace }}
  annotations:
    {{- if .Values.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.basicAuth.secretName }}
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/kibana/(.*)$ /$1 break;
      proxy_set_header Authorization "";
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  tls:
    - hosts:
        - {{ .Values.frontend.dns }}
      secretName: {{ .Values.tls }}
  rules:
    - host: {{ .Values.frontend.dns }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: helpos-frontend-service
                port:
                  number: 80
    - host: {{ .Values.frontend.dns }}
      http:
        paths:
          - path: /gw
            pathType: ImplementationSpecific
            backend:
              service:
                name: helpos-gw-service
                port:
                  number: 80
    - host: {{ .Values.frontend.dns }}
      http:
        paths:
          - backend:
              service:
                name: helpos-kibana
                port:
                  number: 5601
            path: /kibana
            pathType: ImplementationSpecific
    - host: {{ .Values.frontend.dns }}
      http:
        paths:
          - backend:
              service:
                name: helpos-pgadmin
                port:
                  number: 80
            path: /pgadmin
            pathType: ImplementationSpecific
    
    