{{- if .Values.gw.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-gw-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-gw
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}