{{- if .Values.helposlog.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-log-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-log
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}