{{- if .Values.nspush.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-nspush-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-nspush
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}