{{- if .Values.ns.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-ns-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-ns
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}