{{- if .Values.org.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-org-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-org
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}