apiVersion: v1
kind: Secret
metadata:
  name: pull-credentials
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: >-
    {{ .Values.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
