{{- if .Values.sts.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-sts-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-sts
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}