{{- if .Values.templateservice.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: helpos-templateservice-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helpos-templateservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: http
{{- end }}