apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpos-uac-service
  namespace: {{ .Values.namespace }}
  annotations:
    {{- if .Values.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.basicAuth.secretName }}
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
    {{- end }}
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  tls:
    - hosts:
        - {{ .Values.uac.dns }}
      secretName: {{ .Values.tls }}
  rules:
    - host: {{ .Values.uac.dns }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: helpos-uac-service
                port:
                  number: 80